################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
S_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
ASM_UPPER_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
ASM_DEPS := 
C_DEPS := 
CC_DEPS := 
ASM_UPPER_DEPS := 
CPP_DEPS := 
S_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
00_src/02_Custom/00_SGD7/03_SGD7S_M3 \
00_src/02_Custom/00_SGD7/00_SpecCommon/Registers \
00_src/02_Custom/00_SGD7/00_SpecCommon/DataTrace \
00_src/02_Custom/00_SGD7/00_SpecCommon/AnalogMonitor \
00_src/01_Standard/Kernel/ScanC \
00_src/01_Standard/Kernel/ScanB \
00_src/01_Standard/Kernel/ScanA \
00_src/01_Standard/Kernel/Round/UtilityFuns \
00_src/01_Standard/Kernel/Round \
00_src/01_Standard/Kernel/Round/Registers \
00_src/01_Standard/Kernel/Round/OpeIf \
00_src/01_Standard/Kernel/Round/MsgIf \
00_src/01_Standard/Kernel/Round/Core \
00_src/01_Standard/Kernel/Round/Apl/ZSearch \
00_src/01_Standard/Kernel/Round/Apl/VibSup \
00_src/01_Standard/Kernel/Round/Apl/VibLvlInit \
00_src/01_Standard/Kernel/Round/Apl/VMonitor \
00_src/01_Standard/Kernel/Round/Apl/TuneLvlSet \
00_src/01_Standard/Kernel/Round/Apl/TestMode \
00_src/01_Standard/Kernel/Round/Apl/SvMotOpID \
00_src/01_Standard/Kernel/Round/Apl/SoftVer \
00_src/01_Standard/Kernel/Round/Apl/SoftReset \
00_src/01_Standard/Kernel/Round/Apl/SOrigSet \
00_src/01_Standard/Kernel/Round/Apl/RegEdit \
00_src/01_Standard/Kernel/Round/Apl/RefAAT \
00_src/01_Standard/Kernel/Round/Apl/RamEdit \
00_src/01_Standard/Kernel/Round/Apl/PrmInit \
00_src/01_Standard/Kernel/Round/Apl/PrmDownload \
00_src/01_Standard/Kernel/Round/Apl/PoleDetect \
00_src/01_Standard/Kernel/Round/Apl/PJog \
00_src/01_Standard/Kernel/Round/Apl/OptInit \
00_src/01_Standard/Kernel/Round/Apl/OnePrmTun \
00_src/01_Standard/Kernel/Round/Apl/MturnLmtSet \
00_src/01_Standard/Kernel/Round/Apl/MturnClr \
00_src/01_Standard/Kernel/Round/Apl/MotorInfo \
00_src/01_Standard/Kernel/Round/Apl/MonZeroAdj \
00_src/01_Standard/Kernel/Round/Apl/MonGainAdj \
00_src/01_Standard/Kernel/Round/Apl/Jog \
00_src/01_Standard/Kernel/Round/Apl/EasyFFT \
00_src/01_Standard/Kernel/Round/Apl/CurManuAdj \
00_src/01_Standard/Kernel/Round/Apl/CurAutoAdj \
00_src/01_Standard/Kernel/Round/Apl/BFanLtRst \
00_src/01_Standard/Kernel/Round/Apl/AnlgRefManAdj \
00_src/01_Standard/Kernel/Round/Apl/AnlgRefAutoAdj \
00_src/01_Standard/Kernel/Round/Apl/AlmTrc \
00_src/01_Standard/Kernel/Round/Apl/AlmHistClr \
00_src/01_Standard/Kernel/Round/Apl/AccessSet \
00_src/01_Standard/Kernel/Round/Apl/AVibSup \
00_src/01_Standard/Kernel/Round/Apl/AAT \
00_src/01_Standard/Kernel/Lib \
00_src/01_Standard/Kernel/Driver \
00_src/01_Standard/Kernel/Driver/JL086/UDL/Servo \
00_src/01_Standard/Kernel/Driver/JL086/UDL/M3 \
00_src/01_Standard/Kernel/Driver/JL086/CortexR4 \
00_src/01_Standard/Kernel/Boot \
00_src/01_Standard/Kernel/Boot/Config \
00_src/01_Standard/Communications/M3/Motion \
00_src/01_Standard/Communications/M3/MLink \
00_src/01_Standard/Communications/M3 \
00_src/01_Standard/BaseSequences \
00_src/01_Standard/BaseControls \
00_src/00_Bsp/JL086_bsp \

